apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: spring-1811
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: spring-1811 
  name: spring-1811
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: spring-1811
    weight: 100 
